spring.application.name=backend
# spring.mongodb.uri=mongodb://localhost:27017/Docker-Mongo
spring.mongodb.uri = mongodb+srv://01357115-Exercise11_db_user:jqOyXreMlAw9CLfN@cluster0.ux3b1kf.mongodb.net/Docker-Mongo?appName=Cluster0